export const gameSeedData = [
    { title: "EarthBound", image: "/EB.jpg", category: "rpg", isOwned: false },
    {
        title: "The Legend of Zelda",
        image: "/LOZOOT.jpg",
        category: "adventure",
        isOwned: false,
    },
    {
        title: "Pokemon Platinum",
        image: "/PP.png",
        category: "rpg",
        isOwned: false,
    },
    {
        title: "Super Mario 64",
        image: "/SM64.jpg",
        category: "platformer",
        isOwned: false,
    },
    {
        title: "Goldeneye",
        image: "/Goldeneye.jpg",
        category: "shooter",
        isOwned: false,
    },
    {
        title: "Super Mario World",
        image: "/SMW.png",
        category: "platformer",
        isOwned: false,
    },
    {
        title: "Pokemon Emerald",
        image: "/PE.png",
        category: "rpg",
        isOwned: false,
    },
    {
        title: "Chrono Trigger",
        image: "/ChronoTrigger.jpg",
        category: "rpg",
        isOwned: false,
    },
    {
        title: "Donkey Kong Country",
        image: "/DKC.jpg",
        category: "platformer",
        isOwned: false,
    },
    {
        title: "Metroid Prime",
        image: "/MetroidPrime.jpg",
        category: "shooter",
        isOwned: false,
    },
];

export const profileSeedData = [
    {
        id: "u1",
        name: "Dara W",
        displayName: "PlayerOne",
        bio: "I like story-rich games.",
        avatarUrl: null,
        updatedAt: new Date("2026-03-27T16:54:51Z"),
    },
    {
        id: "u2",
        name: "Madeleine Madden",
        displayName: "Player2",
        bio: "I like free games.",
        avatarUrl: null,
        updatedAt: new Date("2026-03-27T16:54:51Z"),
    },
    {
        id: "u3",
        name: "Josha Sadowski",
        displayName: "Player3",
        bio: "I like story-rich games.",
        avatarUrl: null,
        updatedAt: new Date("2026-03-27T16:54:51Z"),
    },
    {
        id: "u4",
        name: "Kate Fleetwood",
        displayName: "Player4",
        bio: "I like animation games.",
        avatarUrl: null,
        updatedAt: new Date("2026-03-27T16:54:51Z"),
    },
    {
        id: "u5",
        name: "Priyanka Bose",
        displayName: "Player5",
        bio: "I like story-rich games.",
        avatarUrl: null,
        updatedAt: new Date("2026-03-27T16:54:51Z"),
    },
    {
        id: "u6",
        name: "Hammed Animashaun",
        displayName: "Player6",
        bio: "I like racing games.",
        avatarUrl: null,
        updatedAt: new Date("2026-03-27T16:54:51Z"),
    },
    {
        id: "u7",
        name: "Álvaro Morte",
        displayName: "Player7",
        bio: "I like casual games.",
        avatarUrl: null,
        updatedAt: new Date("2026-03-27T16:54:51Z"),
    },
    {
        id: "u8",
        name: "Taylor Napier",
        displayName: "Player8",
        bio: "I like newest games.",
        avatarUrl: null,
        updatedAt: new Date("2026-03-27T16:54:51Z"),
    },
    {
        id: "u9",
        name: "Alan Simmonds",
        displayName: "Player9",
        bio: "I like story-rich games.",
        avatarUrl: null,
        updatedAt: new Date("2026-03-27T16:54:51Z"),
    },
    {
        id: "u10",
        name: "Gil Cardinal",
        displayName: "Player10",
        bio: "I like all kind of games.",
        avatarUrl: null,
        updatedAt: new Date("2026-03-27T16:54:51Z"),
    },
];
