import type { UserProfile } from "../types/UserProfile";

export const USER_PROFILES_TESTDATA: UserProfile[] = [
    {
        id: "u1",
        name: "Dara W",
        displayName: "PlayerOne",
        bio: "I like story-rich games.",
        avatarUrl: null,
        updatedAt: new Date().toISOString(),
    },

    {
        id: "u2",
        name: "Madeleine Madden",
        displayName: "Player2",
        bio: "I like free games.",
        avatarUrl: null,
        updatedAt: new Date().toISOString(),
    },
    {
        id: "u3",
        name: "Josha Sadowski",
        displayName: "Player3",
        bio: "I like story-rich games.",
        avatarUrl: null,
        updatedAt: new Date().toISOString(),
    },
    {
        id: "u4",
        name: "Kate Fleetwood",
        displayName: "Player4",
        bio: "I like animation games.",
        avatarUrl: null,
        updatedAt: new Date().toISOString(),
    },
    {
        id: "u5",
        name: "Priyanka Bose",
        displayName: "Player5",
        bio: "I like story-rich games.",
        avatarUrl: null,
        updatedAt: new Date().toISOString(),
    },
    {
        id: "u6",
        name: "Hammed Animashaun",
        displayName: "Player6",
        bio: "I like racing games.",
        avatarUrl: null,
        updatedAt: new Date().toISOString(),
    },
    {
        id: "u7",
        name: "Álvaro Morte",
        displayName: "Player7",
        bio: "I like casual games.",
        avatarUrl: null,
        updatedAt: new Date().toISOString(),
    },
    {
        id: "u8",
        name: "Taylor Napier",
        displayName: "Player8",
        bio: "I like newest games.",
        avatarUrl: null,
        updatedAt: new Date().toISOString(),
    },
    {
        id: "u9",
        name: "Alan Simmonds",
        displayName: "Player9",
        bio: "I like story-rich games.",
        avatarUrl: null,
        updatedAt: new Date().toISOString(),
    },
    {
        id: "u10",
        name: "Gil Cardinal",
        displayName: "Player10",
        bio: "I like all kind of games.",
        avatarUrl: null,
        updatedAt: new Date().toISOString(),
    },
];
